import jsPDF from "jspdf";
import html2canvas from "html2canvas";

// Generate PDF from component data
export const generatePDFReport = async (
  data: any,
  title: string,
  format: "pdf" | "image" = "pdf"
) => {
  try {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();

    // Add title
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text(title, 20, 30);

    // Add generation date
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 45);

    let yPosition = 60;

    // Add data sections based on the type of report
    if (data.sections) {
      for (const section of data.sections) {
        // Check if we need a new page
        if (yPosition > pageHeight - 40) {
          pdf.addPage();
          yPosition = 30;
        }

        // Add section title
        pdf.setFontSize(16);
        pdf.setFont("helvetica", "bold");
        pdf.text(section.title, 20, yPosition);
        yPosition += 15;

        // Add section content
        pdf.setFontSize(10);
        pdf.setFont("helvetica", "normal");

        if (section.type === "metrics") {
          // Add metrics data
          section.data.forEach((metric: any) => {
            const metricText = `${metric.label}: ${metric.value}`;
            pdf.text(metricText, 25, yPosition);
            yPosition += 8;
          });
        } else if (section.type === "chartData") {
          // Add chart information
          pdf.text("Chart Data:", 25, yPosition);
          yPosition += 10;
          section.data.forEach((item: any) => {
            const itemText = `• ${item.name}: ${item.value}`;
            pdf.text(itemText, 30, yPosition);
            yPosition += 6;
          });
        }

        yPosition += 10;
      }
    }

    // Add footer
    const pageCount = (pdf as any).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.text(
        `Page ${i} of ${pageCount} | Generated by EcoMetrics`,
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );
    }

    // Generate filename
    const filename = `${title.toLowerCase().replace(/\s+/g, "-")}-${
      new Date().toISOString().split("T")[0]
    }.pdf`;

    if (format === "pdf") {
      // Save PDF
      pdf.save(filename);
    } else {
      // Convert to image and download
      const pdfDataUrl = pdf.output("datauristring");
      // For image format, we would need additional processing
      const canvas = document.createElement("canvas");
      canvas.width = pageWidth * 2;
      canvas.height = pageHeight * 2;
      const ctx = canvas.getContext("2d")!;

      // This is a simplified approach - in practice, you'd use a PDF to image library
      const img = new Image();
      img.onload = () => {
        ctx.drawImage(img, 0, 0);
        canvas.toBlob((blob) => {
          if (blob) {
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = filename.replace(".pdf", ".png");
            a.click();
            URL.revokeObjectURL(url);
          }
        });
      };
      img.src = pdfDataUrl;
    }

    return { success: true, filename };
  } catch (error) {
    console.error("Error generating PDF:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
};

// Generate real-time carbon tracking report
export const generateCarbonTrackingReport = (data: any) => {
  const reportData = {
    sections: [
      {
        title: "Current Emissions Summary",
        type: "metrics" as const,
        data: [
          {
            label: "Current Emissions",
            value: `${data.currentEmissions} tCO₂e`,
          },
          { label: "Daily Target", value: "320 tCO₂e" },
          { label: "Week Progress", value: "73%" },
          { label: "Cost Impact", value: "R23,070" },
        ],
      },
      {
        title: "Emission Sources",
        type: "chartData" as const,
        data: data.emissionSources || [],
      },
      {
        title: "Weekly Comparison",
        type: "chartData" as const,
        data: data.dailyComparison || [],
      },
      {
        title: "Recent Alerts",
        type: "chartData" as const,
        data: (data.alerts || []).map((alert: any) => ({
          name: alert.message,
          value: alert.type,
        })),
      },
    ],
  };

  return generatePDFReport(reportData, "Carbon Emissions Tracking Report");
};

// Generate emission source breakdown report
export const generateEmissionBreakdownReport = (data: any) => {
  const reportData = {
    sections: [
      {
        title: "Scope Breakdown Summary",
        type: "metrics" as const,
        data: [
          { label: "Scope 1 Emissions", value: "1,110 tCO₂e" },
          { label: "Scope 2 Emissions", value: "700 tCO₂e" },
          { label: "Scope 3 Emissions", value: "820 tCO₂e" },
          { label: "Total Emissions", value: "2,630 tCO₂e" },
        ],
      },
      {
        title: "Reduction Opportunities",
        type: "chartData" as const,
        data: (data.reductionOpportunities || []).map((opp: any) => ({
          name: opp.source,
          value: `${opp.potential} tCO₂e potential (${opp.impact} impact)`,
        })),
      },
    ],
  };

  return generatePDFReport(reportData, "Emission Source Breakdown Report");
};

// Generate automated reports summary
export const generateAutomatedReportsSummary = (data: any) => {
  const reportData = {
    sections: [
      {
        title: "KPI Summary",
        type: "metrics" as const,
        data: [
          { label: "Carbon Intensity", value: "245.8 tCO₂e/R" },
          { label: "Energy Efficiency", value: "87.3%" },
          { label: "Renewable Energy", value: "62.1%" },
          { label: "Waste Diversion", value: "78.9%" },
        ],
      },
      {
        title: "Department Performance",
        type: "chartData" as const,
        data: (data.departmentEmissions || []).map((dept: any) => ({
          name: dept.department,
          value: `${dept.emissions} / ${dept.target} tCO₂e`,
        })),
      },
    ],
  };

  return generatePDFReport(reportData, "Automated Reports Summary");
};

// Capture and download a screenshot of a DOM element
export const captureElementAsImage = async (
  elementId: string,
  filename?: string
) => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error(`Element with id '${elementId}' not found`);
    }

    const canvas = await html2canvas(element, {
      backgroundColor: "#ffffff",
      scale: 2,
      useCORS: true,
      allowTaint: true,
    });

    const link = document.createElement("a");
    link.download =
      filename || `dashboard-${new Date().toISOString().split("T")[0]}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();

    return { success: true };
  } catch (error) {
    console.error("Error capturing element:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
};
